# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: 'no'
    environment:
      MARIADB_ROOT_PASSWORD: battleships
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: 'no'
    ports:
      - 8080:8080
